# A default tauri test action
name: "test-app"
on: [pull_request]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      
      - name: go to password generator
        run: |
          cd $GITHUB_WORKSPACE
          cd ./password-generator

      - name: test the wasm-library
        run: cargo test --verbose 

      - name: compile password-generator wasm library
        run: |
          cargo install wasm-pack
          wasm-pack build --target bundler
          cd ./pkg
          npm link

      - name: return back and link password-generator
        run: |
          cd $GITHUB_WORKSPACE
          npm link password-generator

      - name: install frontend dependencies
        run: npm install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}